"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import sys

with open('requirements.txt') as f:
    required = f.read().splitlines()

    APP = ['minesweeper/main.py']
    DATA_FILES = [('', ['assets'])]
    OPTIONS = {'iconfile':'assets/icon.icns'}

    if sys.platform == 'darwin':
        extra_options = dict(
            app=APP,
            setup_requires=['py2app']+required,
            # Cross-platform applications generally expect sys.argv to
            # be used for opening files.
            options=dict(py2app=dict(argv_emulation=True)),
        )
    elif sys.platform == 'win32':
        import py2exe
        extra_options = dict(
            setup_requires=['py2exe']+required
        )
    setup(
        name="Minesw33per",
        data_files=DATA_FILES,
        **extra_options
    )